// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServiceApiClient is the client API for ChatServiceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceApiClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type chatServiceApiClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceApiClient(cc grpc.ClientConnInterface) ChatServiceApiClient {
	return &chatServiceApiClient{cc}
}

func (c *chatServiceApiClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatServiceApi/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceApiServer is the server API for ChatServiceApi service.
// All implementations should embed UnimplementedChatServiceApiServer
// for forward compatibility
type ChatServiceApiServer interface {
	SayHello(context.Context, *Message) (*Message, error)
}

// UnimplementedChatServiceApiServer should be embedded to have forward compatible implementations.
type UnimplementedChatServiceApiServer struct {
}

func (UnimplementedChatServiceApiServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

// UnsafeChatServiceApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceApiServer will
// result in compilation errors.
type UnsafeChatServiceApiServer interface {
	mustEmbedUnimplementedChatServiceApiServer()
}

func RegisterChatServiceApiServer(s grpc.ServiceRegistrar, srv ChatServiceApiServer) {
	s.RegisterService(&ChatServiceApi_ServiceDesc, srv)
}

func _ChatServiceApi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceApiServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatServiceApi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceApiServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatServiceApi_ServiceDesc is the grpc.ServiceDesc for ChatServiceApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatServiceApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatServiceApi",
	HandlerType: (*ChatServiceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ChatServiceApi_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
